### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by mikeymike** [EugenMayer/docker_sync#2]
Hey @EugenMayer ... first off thanks for making this project, performance has become a real pain for us after moving to docker last week. 

I'm not sure if I'm just doing something wrong or what but atm the files are coming through as `nobody nogroup` and my app loses permissions to write cache etc. 

`docker-sync.yml`
```yml
syncs:
  app_vol:
    src: './'
    dest: '/var/www/magento'
    sync_host_ip: 'localhost'
    sync_host_port: 10871
  db_vol:
    src: './.docker/mysql'
    dest: '/var/lib/mysql'
    sync_host_ip: 'localhost'
    sync_host_port: 1087
```

`docker-compose.yml` _simplyfied_ 
```yml
version: '2'
volumes:
    app_vol:
        external: true
    db_vol:
        external: true

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        volumes_from:
            - container:app_vol:rw
        volumes:
#            - "./:/var/www/magento"
            - "./.docker/sites:/etc/nginx/conf.d"
        ports:
            - "80:80"
        links:
            - php
        env_file:
            - ./project.env

    db:
        container_name: db
        image: mysql:5.6
        volumes_from:
              - container:db_vol:rw
        volumes:
#            - "./.docker/mysql:/var/lib/mysql"
            - "./.docker/db/:/docker-entrypoint-initdb.d/"
        ports:
            - "3306:3306"
        restart: always
        env_file:
            - ./project.env

    php:
        container_name: php
        image: mikeymike/docker-php
        volumes_from:
            - container:app_vol:rw
        volumes:
#            - "./:/var/www/magento"
            - "${HOME}/.composer:/root/.composer"
            - "${HOME}/.ssh:/root/.ssh"
        working_dir: /var/www/magento
        ports:
            - 9000
        links:
            - db
        env_file:
            - ./project.env
```

Any thoughts on this would be awesome :D
