### ISSUE TITLE
Started, but not syncing unless on restart of docker-sync

### ISSUE THREAD

**Issue by iwaffles** [EugenMayer/docker_sync#5]
I've managed to get docker-sync running and it seems to share the volume data when I initially run `docker-sync start`, however, after editing anything in the directory that it's watching it doesn't appear to sync any data.

Restarting docker-sync shows a new set of data, but that defeats the purpose of running it once and letting data sync when saved/updated.

Is there possibly a step I'm missing here? I don't have any watch excludes setup and I'm using rsync 3.1.2 on OS X. I don't see any errors in the logs, either.

**Comment by iwaffles** [comment]
For what it's worth I tried running the `fswatch` command with thor manually and it seems to return `Could not find command "sync:sync".`

**Comment by EugenMayer** [comment]
@iwaffles thats for sure not the desired behavior. Which gem version are you using? looks like you are below < 0.0.7? if yes, please upgrae.

Could you paste your docker-sync.yml?

**Comment by iwaffles** [comment]
Ah yes it appears that I'm on 0.0.5. Upgraded to 0.0.8 and all seems to be working!

Great work @EugenMayer!

**Comment by iwaffles** [comment]
For what it's worth, here's my docker-sync file:

```yaml
options:
  # verbose: true
syncs:
  appcode:
    src: '.'
    dest: '/app'
    sync_host_ip: 'localhost'
    sync_host_port: 9999
    sync_strategy: 'rsync'
```
